### ISSUE TITLE
if there are spaces in tags, the string gets truncated

### ISSUE THREAD

**Issue by andy5995** [ismnoiet/jekyll-posts-generator#5]
if there are spaces in tags, the string gets truncated

This only applies to an unmerged patch (#1)

If a tag string is:
berry,blueberry,Max Berry,Smurfberry

The tags added to the post will be:
- berry
- blueberry
- Max

It will also truncate at the first occurrence of a space if it's after a comma.

This probably was unnoticed before with categories since they are less likely to contain spaces. 

@ismnoiet you may have noticed I only copied the category code and changed all instances of `category` to `tag`

**Comment by andy5995** [comment]
The fix for this is hinted at in https://github.com/ismnoiet/jekyll-posts-generator/issues/4#issuecomment-340658957

**Comment by ismnoiet** [comment]
Fixed in version `0.0.6`.
